import { Distributor } from "./types";

export const DISTRIBUTORS: Distributor[] = [
  {
    id: "server2u-my",
    name: "Server2U",
    country: "Malaysia",
    countryFlag: "🇲🇾",
    region: "Asia-Pacific",
    website: "https://server2u.com",
    paymentMethods: ["Credit Card", "Online Payment"],
    notes: "In-stock, fastest to Thailand",
  },
  {
    id: "linitx-uk",
    name: "Linitx",
    country: "United Kingdom",
    countryFlag: "🇬🇧",
    region: "Europe",
    website: "https://linitx.com",
    paymentMethods: [
      "Credit Card",
      "Bank Transfer",
      "Apple Pay",
      "Revolut Pay",
      "Invoice",
    ],
  },
  {
    id: "interprojekt-pl",
    name: "Inter Projekt",
    country: "Poland",
    countryFlag: "🇵🇱",
    region: "Europe",
    website: "https://interprojekt.pl",
    paymentMethods: ["Online Payment", "Bank Transfer", "Credit Card"],
    notes: "Best overall price",
  },
  {
    id: "nasstore-eu",
    name: "NAS Store EU",
    country: "European Union",
    countryFlag: "🇪🇺",
    region: "Europe",
    website: "https://nasstore.eu",
    paymentMethods: [
      "Credit Card",
      "Bank Transfer",
      "Apple Pay",
      "Revolut Pay",
    ],
    notes: "Best August price",
  },
  {
    id: "aerial-gr",
    name: "Aerial.net",
    country: "Greece",
    countryFlag: "🇬🇷",
    region: "Europe",
    website: "https://aerial.net",
    paymentMethods: ["Credit Card", "Bank Transfer"],
  },
  {
    id: "mikrotikstore-de",
    name: "MikroTik Store EU",
    country: "Germany",
    countryFlag: "🇩🇪",
    region: "Europe",
    website: "https://mikrotik-store.eu",
    paymentMethods: ["Credit Card", "PayPal", "Bank Transfer"],
    notes: "Official MikroTik certified distributor",
  },
  {
    id: "miro-za",
    name: "MiRO Distribution",
    country: "South Africa",
    countryFlag: "🇿🇦",
    region: "Africa",
    website: "https://miro.co.za",
    paymentMethods: ["Credit Card", "EFT"],
  },
  {
    id: "gearup-ae",
    name: "Gear-Up.me",
    country: "UAE",
    countryFlag: "🇦🇪",
    region: "Middle East",
    website: "https://gear-up.me",
    paymentMethods: ["Credit Card", "Bank Transfer"],
    notes: "24-month local warranty",
  },
  {
    id: "balticnetworks-us",
    name: "Baltic Networks",
    country: "United States",
    countryFlag: "🇺🇸",
    region: "North America",
    website: "https://balticnetworks.com",
    paymentMethods: ["Wire Transfer"],
    notes: "Wire transfer only",
  },
  {
    id: "linktechs-us",
    name: "Link Technologies",
    country: "United States",
    countryFlag: "🇺🇸",
    region: "North America",
    website: "https://shop.linktechs.net",
    paymentMethods: ["Wire Transfer"],
    notes: "Wire transfer only",
  },
  {
    id: "winncom-us",
    name: "Winncom",
    country: "United States",
    countryFlag: "🇺🇸",
    region: "North America",
    website: "https://winncom.com",
    paymentMethods: ["Credit Card", "Bank Transfer"],
  },
  {
    id: "bhphoto-us",
    name: "B&H Photo Video",
    country: "United States",
    countryFlag: "🇺🇸",
    region: "North America",
    website: "https://bhphotovideo.com",
    paymentMethods: ["Credit Card", "PayPal", "Financing"],
  },
  {
    id: "duxtel-au",
    name: "DuxTel",
    country: "Australia",
    countryFlag: "🇦🇺",
    region: "Asia-Pacific",
    website: "https://store.duxtel.com",
    paymentMethods: ["Credit Card", "Bank Transfer"],
  },
  {
    id: "wisp-au",
    name: "WISP",
    country: "Australia",
    countryFlag: "🇦🇺",
    region: "Asia-Pacific",
    website: "https://wisp.net.au",
    paymentMethods: ["Credit Card"],
  },
  {
    id: "pbtech-nz",
    name: "PB Tech",
    country: "New Zealand",
    countryFlag: "🇳🇿",
    region: "Asia-Pacific",
    website: "https://pbtech.co.nz",
    paymentMethods: ["Credit Card", "Bank Transfer", "Afterpay"],
  },
  {
    id: "gowifi-nz",
    name: "GoWiFi",
    country: "New Zealand",
    countryFlag: "🇳🇿",
    region: "Asia-Pacific",
    website: "https://gowifi.co.nz",
    paymentMethods: ["Credit Card"],
  },
  {
    id: "getic-gr",
    name: "Getic",
    country: "Greece",
    countryFlag: "🇬🇷",
    region: "Europe",
    website: "https://getic.com",
    paymentMethods: ["Credit Card", "Bank Transfer"],
  },
  {
    id: "100mega-cz",
    name: "100MEGA Distribution",
    country: "Czech Republic",
    countryFlag: "🇨🇿",
    region: "Europe",
    website: "https://b2b.100mega.com",
    paymentMethods: ["Bank Transfer", "Credit Card"],
  },
  {
    id: "hellascom-gr",
    name: "HellasCom",
    country: "Greece",
    countryFlag: "🇬🇷",
    region: "Europe",
    website: "https://hellascom.gr",
    paymentMethods: ["Credit Card", "Bank Transfer"],
    notes: "MikroTik distributor since 2001, ISO 9001:2015",
  },
  {
    id: "rocnoc-us",
    name: "ROC-NOC",
    country: "United States",
    countryFlag: "🇺🇸",
    region: "North America",
    website: "https://roc-noc.com",
    paymentMethods: ["Credit Card", "Bank Transfer"],
  },
  {
    id: "networkdevices-us",
    name: "Network Devices Inc",
    country: "United States",
    countryFlag: "🇺🇸",
    region: "North America",
    website: "https://networkdevicesinc.com",
    paymentMethods: ["Credit Card", "Bank Transfer"],
  },
  {
    id: "flytec-us",
    name: "Flytec Computers",
    country: "United States",
    countryFlag: "🇺🇸",
    region: "North America",
    website: "https://flyteccomputers.com",
    paymentMethods: ["Credit Card"],
  },
  {
    id: "mbsiwav-ca",
    name: "MBS I-WAV",
    country: "Canada",
    countryFlag: "🇨🇦",
    region: "North America",
    website: "https://mbsiwav.com",
    paymentMethods: ["Credit Card", "Bank Transfer"],
  },
  {
    id: "multilink-us",
    name: "Multilink",
    country: "United States",
    countryFlag: "🇺🇸",
    region: "North America",
    website: "https://shop.multilink.us",
    paymentMethods: ["Credit Card"],
  },
  {
    id: "neobits-us",
    name: "Neobits",
    country: "United States",
    countryFlag: "🇺🇸",
    region: "North America",
    website: "https://neobits.com",
    paymentMethods: ["Credit Card", "PayPal"],
  },
];

export function getDistributorById(id: string): Distributor | undefined {
  return DISTRIBUTORS.find((d) => d.id === id);
}

export function getDistributorsByRegion(region: string): Distributor[] {
  return DISTRIBUTORS.filter((d) => d.region === region);
}
