import { DistributorListing } from "@/lib/types";

const d = (daysAgo: number) =>
  new Date(Date.now() - 86400000 * daysAgo).toISOString();

export const SAMPLE_LISTINGS: Record<string, DistributorListing[]> = {
  "mikrotik-crs804-4ddq-hrm": [
    {
      distributorId: "server2u-my",
      productId: "mikrotik-crs804-4ddq-hrm",
      price: 5568,
      currency: "MYR",
      stockStatus: "in_stock",
      url: "https://server2u.com/shop/crs804-4ddq-hrm-mikrotik-crs804-4ddq-hrm-400g-master-switch-66247",
      lastChecked: new Date().toISOString(),
      priceHistory: [
        { date: d(90), price: 5900, currency: "MYR", stockStatus: "in_stock" },
        { date: d(75), price: 5850, currency: "MYR", stockStatus: "in_stock" },
        { date: d(60), price: 5800, currency: "MYR", stockStatus: "in_stock" },
        { date: d(45), price: 5780, currency: "MYR", stockStatus: "in_stock" },
        { date: d(30), price: 5750, currency: "MYR", stockStatus: "in_stock" },
        { date: d(21), price: 5680, currency: "MYR", stockStatus: "in_stock" },
        { date: d(14), price: 5620, currency: "MYR", stockStatus: "in_stock" },
        { date: d(7), price: 5590, currency: "MYR", stockStatus: "in_stock" },
        { date: d(3), price: 5575, currency: "MYR", stockStatus: "in_stock" },
        { date: d(0), price: 5568, currency: "MYR", stockStatus: "in_stock" },
      ],
    },
    {
      distributorId: "mikrotikstore-de",
      productId: "mikrotik-crs804-4ddq-hrm",
      price: 1141.67,
      currency: "EUR",
      stockStatus: "in_stock",
      url: "https://mikrotik-store.eu/en/cloud-router-switches/crs804-4ddq-hrm",
      lastChecked: new Date().toISOString(),
      priceHistory: [
        { date: d(90), price: 1050, currency: "EUR", stockStatus: "in_stock" },
        { date: d(75), price: 1065, currency: "EUR", stockStatus: "in_stock" },
        { date: d(60), price: 1080, currency: "EUR", stockStatus: "in_stock" },
        { date: d(45), price: 1090, currency: "EUR", stockStatus: "in_stock" },
        { date: d(30), price: 1095, currency: "EUR", stockStatus: "in_stock" },
        { date: d(21), price: 1110, currency: "EUR", stockStatus: "in_stock" },
        { date: d(14), price: 1125, currency: "EUR", stockStatus: "in_stock" },
        { date: d(7), price: 1135, currency: "EUR", stockStatus: "in_stock" },
        { date: d(3), price: 1139, currency: "EUR", stockStatus: "in_stock" },
        {
          date: d(0),
          price: 1141.67,
          currency: "EUR",
          stockStatus: "in_stock",
        },
      ],
    },
    {
      distributorId: "interprojekt-pl",
      productId: "mikrotik-crs804-4ddq-hrm",
      price: 860.54,
      currency: "EUR",
      stockStatus: "back_order",
      expectedDate: "Sept 15, 2026",
      url: "https://interprojekt.pl/en/p/mikrotik-crs804-4ddq-hrm.html",
      lastChecked: new Date().toISOString(),
      priceHistory: [
        { date: d(90), price: 920, currency: "EUR", stockStatus: "in_stock" },
        { date: d(75), price: 910, currency: "EUR", stockStatus: "in_stock" },
        { date: d(60), price: 900, currency: "EUR", stockStatus: "back_order" },
        { date: d(45), price: 895, currency: "EUR", stockStatus: "back_order" },
        { date: d(30), price: 890, currency: "EUR", stockStatus: "back_order" },
        { date: d(21), price: 882, currency: "EUR", stockStatus: "back_order" },
        { date: d(14), price: 875, currency: "EUR", stockStatus: "back_order" },
        { date: d(7), price: 868, currency: "EUR", stockStatus: "back_order" },
        { date: d(3), price: 863, currency: "EUR", stockStatus: "back_order" },
        {
          date: d(0),
          price: 860.54,
          currency: "EUR",
          stockStatus: "back_order",
        },
      ],
    },
    {
      distributorId: "nasstore-eu",
      productId: "mikrotik-crs804-4ddq-hrm",
      price: 956.0,
      currency: "EUR",
      stockStatus: "back_order",
      expectedDate: "Aug 13, 2026",
      url: "https://nasstore.eu/product/mikrotik-cloud-router-switch-crs804-4ddq-hrm/",
      lastChecked: new Date().toISOString(),
      priceHistory: [
        { date: d(90), price: 990, currency: "EUR", stockStatus: "in_stock" },
        { date: d(75), price: 985, currency: "EUR", stockStatus: "in_stock" },
        { date: d(60), price: 980, currency: "EUR", stockStatus: "back_order" },
        { date: d(45), price: 975, currency: "EUR", stockStatus: "back_order" },
        { date: d(30), price: 970, currency: "EUR", stockStatus: "back_order" },
        { date: d(21), price: 968, currency: "EUR", stockStatus: "back_order" },
        { date: d(14), price: 965, currency: "EUR", stockStatus: "back_order" },
        { date: d(7), price: 960, currency: "EUR", stockStatus: "back_order" },
        { date: d(3), price: 958, currency: "EUR", stockStatus: "back_order" },
        { date: d(0), price: 956, currency: "EUR", stockStatus: "back_order" },
      ],
    },
    {
      distributorId: "aerial-gr",
      productId: "mikrotik-crs804-4ddq-hrm",
      price: 956.99,
      currency: "EUR",
      stockStatus: "back_order",
      expectedDate: "Sept 9, 2026",
      url: "https://aerial.net/shop/product/mikrotik-crs804-4ddq-hrm-cloud-router-switch-5671",
      lastChecked: new Date().toISOString(),
      priceHistory: [
        { date: d(90), price: 995, currency: "EUR", stockStatus: "in_stock" },
        { date: d(75), price: 990, currency: "EUR", stockStatus: "in_stock" },
        { date: d(60), price: 985, currency: "EUR", stockStatus: "back_order" },
        { date: d(45), price: 980, currency: "EUR", stockStatus: "back_order" },
        { date: d(30), price: 975, currency: "EUR", stockStatus: "back_order" },
        { date: d(21), price: 970, currency: "EUR", stockStatus: "back_order" },
        { date: d(14), price: 965, currency: "EUR", stockStatus: "back_order" },
        { date: d(7), price: 960, currency: "EUR", stockStatus: "back_order" },
        { date: d(3), price: 958, currency: "EUR", stockStatus: "back_order" },
        {
          date: d(0),
          price: 956.99,
          currency: "EUR",
          stockStatus: "back_order",
        },
      ],
    },
    {
      distributorId: "linitx-uk",
      productId: "mikrotik-crs804-4ddq-hrm",
      price: 1139.99,
      currency: "GBP",
      stockStatus: "back_order",
      expectedDate: "Sept 18, 2026",
      url: "https://linitx.com/product/mikrotik-crs804-ddq-cloud-router-400gb-4-port-switch-crs804-4ddq-hrm/18455",
      lastChecked: new Date().toISOString(),
      priceHistory: [
        { date: d(90), price: 1220, currency: "GBP", stockStatus: "in_stock" },
        { date: d(75), price: 1210, currency: "GBP", stockStatus: "in_stock" },
        {
          date: d(60),
          price: 1200,
          currency: "GBP",
          stockStatus: "back_order",
        },
        {
          date: d(45),
          price: 1195,
          currency: "GBP",
          stockStatus: "back_order",
        },
        {
          date: d(30),
          price: 1180,
          currency: "GBP",
          stockStatus: "back_order",
        },
        {
          date: d(21),
          price: 1170,
          currency: "GBP",
          stockStatus: "back_order",
        },
        {
          date: d(14),
          price: 1160,
          currency: "GBP",
          stockStatus: "back_order",
        },
        { date: d(7), price: 1150, currency: "GBP", stockStatus: "back_order" },
        { date: d(3), price: 1144, currency: "GBP", stockStatus: "back_order" },
        {
          date: d(0),
          price: 1139.99,
          currency: "GBP",
          stockStatus: "back_order",
        },
      ],
    },
    {
      distributorId: "miro-za",
      productId: "mikrotik-crs804-4ddq-hrm",
      price: 30140,
      currency: "ZAR",
      stockStatus: "back_order",
      expectedDate: "Aug 2026",
      url: "https://miro.co.za/07-networking-switches---managed-layer-3/8878-mikrotik-cloud-router-switch-crs804-4ddq-hrm-miro.html",
      lastChecked: new Date().toISOString(),
      priceHistory: [
        { date: d(90), price: 28500, currency: "ZAR", stockStatus: "in_stock" },
        { date: d(75), price: 28800, currency: "ZAR", stockStatus: "in_stock" },
        {
          date: d(60),
          price: 29000,
          currency: "ZAR",
          stockStatus: "back_order",
        },
        {
          date: d(45),
          price: 29200,
          currency: "ZAR",
          stockStatus: "back_order",
        },
        {
          date: d(30),
          price: 29500,
          currency: "ZAR",
          stockStatus: "back_order",
        },
        {
          date: d(21),
          price: 29700,
          currency: "ZAR",
          stockStatus: "back_order",
        },
        {
          date: d(14),
          price: 29900,
          currency: "ZAR",
          stockStatus: "back_order",
        },
        {
          date: d(7),
          price: 30000,
          currency: "ZAR",
          stockStatus: "back_order",
        },
        {
          date: d(3),
          price: 30100,
          currency: "ZAR",
          stockStatus: "back_order",
        },
        {
          date: d(0),
          price: 30140,
          currency: "ZAR",
          stockStatus: "back_order",
        },
      ],
    },
    {
      distributorId: "getic-gr",
      productId: "mikrotik-crs804-4ddq-hrm",
      price: 877.64,
      currency: "EUR",
      stockStatus: "out_of_stock",
      url: "https://www.getic.com/product/mikrotik-crs804-4ddq-hrm",
      lastChecked: new Date().toISOString(),
      priceHistory: [
        { date: d(90), price: 855, currency: "EUR", stockStatus: "in_stock" },
        { date: d(75), price: 858, currency: "EUR", stockStatus: "in_stock" },
        { date: d(60), price: 860, currency: "EUR", stockStatus: "in_stock" },
        { date: d(45), price: 865, currency: "EUR", stockStatus: "in_stock" },
        { date: d(30), price: 870, currency: "EUR", stockStatus: "in_stock" },
        { date: d(21), price: 872, currency: "EUR", stockStatus: "in_stock" },
        {
          date: d(14),
          price: 875,
          currency: "EUR",
          stockStatus: "out_of_stock",
        },
        {
          date: d(7),
          price: 876,
          currency: "EUR",
          stockStatus: "out_of_stock",
        },
        {
          date: d(3),
          price: 877,
          currency: "EUR",
          stockStatus: "out_of_stock",
        },
        {
          date: d(0),
          price: 877.64,
          currency: "EUR",
          stockStatus: "out_of_stock",
        },
      ],
    },
    {
      distributorId: "duxtel-au",
      productId: "mikrotik-crs804-4ddq-hrm",
      price: 2299,
      currency: "AUD",
      stockStatus: "out_of_stock",
      url: "https://store.duxtel.com.au/product/crs804-4ddq-hrm",
      lastChecked: new Date().toISOString(),
      priceHistory: [
        { date: d(90), price: 2450, currency: "AUD", stockStatus: "in_stock" },
        { date: d(75), price: 2430, currency: "AUD", stockStatus: "in_stock" },
        { date: d(60), price: 2410, currency: "AUD", stockStatus: "in_stock" },
        { date: d(45), price: 2390, currency: "AUD", stockStatus: "in_stock" },
        { date: d(30), price: 2370, currency: "AUD", stockStatus: "in_stock" },
        { date: d(21), price: 2350, currency: "AUD", stockStatus: "in_stock" },
        {
          date: d(14),
          price: 2330,
          currency: "AUD",
          stockStatus: "out_of_stock",
        },
        {
          date: d(7),
          price: 2310,
          currency: "AUD",
          stockStatus: "out_of_stock",
        },
        {
          date: d(3),
          price: 2305,
          currency: "AUD",
          stockStatus: "out_of_stock",
        },
        {
          date: d(0),
          price: 2299,
          currency: "AUD",
          stockStatus: "out_of_stock",
        },
      ],
    },
  ],

  "mikrotik-crs326-24s": [
    {
      distributorId: "balticnetworks-us",
      productId: "mikrotik-crs326-24s",
      price: 499,
      currency: "USD",
      stockStatus: "in_stock",
      url: "https://balticnetworks.com/mikrotik-crs326-24s-2q-rm.html",
      lastChecked: new Date().toISOString(),
      priceHistory: [
        {
          date: new Date(Date.now() - 86400000 * 90).toISOString(),
          price: 540,
          currency: "USD",
          stockStatus: "in_stock",
        },
        {
          date: new Date(Date.now() - 86400000 * 75).toISOString(),
          price: 535,
          currency: "USD",
          stockStatus: "in_stock",
        },
        {
          date: new Date(Date.now() - 86400000 * 60).toISOString(),
          price: 530,
          currency: "USD",
          stockStatus: "in_stock",
        },
        {
          date: new Date(Date.now() - 86400000 * 45).toISOString(),
          price: 525,
          currency: "USD",
          stockStatus: "in_stock",
        },
        {
          date: new Date(Date.now() - 86400000 * 30).toISOString(),
          price: 520,
          currency: "USD",
          stockStatus: "in_stock",
        },
        {
          date: new Date(Date.now() - 86400000 * 21).toISOString(),
          price: 515,
          currency: "USD",
          stockStatus: "in_stock",
        },
        {
          date: new Date(Date.now() - 86400000 * 14).toISOString(),
          price: 510,
          currency: "USD",
          stockStatus: "in_stock",
        },
        {
          date: new Date(Date.now() - 86400000 * 7).toISOString(),
          price: 505,
          currency: "USD",
          stockStatus: "in_stock",
        },
        {
          date: new Date(Date.now() - 86400000 * 3).toISOString(),
          price: 502,
          currency: "USD",
          stockStatus: "in_stock",
        },
        {
          date: new Date().toISOString(),
          price: 499,
          currency: "USD",
          stockStatus: "in_stock",
        },
      ],
    },
    {
      distributorId: "interprojekt-pl",
      productId: "mikrotik-crs326-24s",
      price: 389,
      currency: "EUR",
      stockStatus: "in_stock",
      url: "https://interprojekt.pl/en/p/mikrotik-crs326-24s.html",
      lastChecked: new Date().toISOString(),
      priceHistory: [
        {
          date: new Date(Date.now() - 86400000 * 90).toISOString(),
          price: 420,
          currency: "EUR",
          stockStatus: "in_stock",
        },
        {
          date: new Date(Date.now() - 86400000 * 60).toISOString(),
          price: 415,
          currency: "EUR",
          stockStatus: "in_stock",
        },
        {
          date: new Date(Date.now() - 86400000 * 30).toISOString(),
          price: 405,
          currency: "EUR",
          stockStatus: "in_stock",
        },
        {
          date: new Date(Date.now() - 86400000 * 14).toISOString(),
          price: 398,
          currency: "EUR",
          stockStatus: "in_stock",
        },
        {
          date: new Date(Date.now() - 86400000 * 7).toISOString(),
          price: 393,
          currency: "EUR",
          stockStatus: "in_stock",
        },
        {
          date: new Date().toISOString(),
          price: 389,
          currency: "EUR",
          stockStatus: "in_stock",
        },
      ],
    },
    {
      distributorId: "mikrotikstore-de",
      productId: "mikrotik-crs326-24s",
      price: 415,
      currency: "EUR",
      stockStatus: "in_stock",
      url: "https://mikrotik-store.eu/en/cloud-router-switches/crs326-24s-2q-rm",
      lastChecked: new Date().toISOString(),
      priceHistory: [
        {
          date: new Date(Date.now() - 86400000 * 60).toISOString(),
          price: 430,
          currency: "EUR",
          stockStatus: "in_stock",
        },
        {
          date: new Date(Date.now() - 86400000 * 30).toISOString(),
          price: 425,
          currency: "EUR",
          stockStatus: "in_stock",
        },
        {
          date: new Date(Date.now() - 86400000 * 14).toISOString(),
          price: 420,
          currency: "EUR",
          stockStatus: "in_stock",
        },
        {
          date: new Date().toISOString(),
          price: 415,
          currency: "EUR",
          stockStatus: "in_stock",
        },
      ],
    },
    {
      distributorId: "linitx-uk",
      productId: "mikrotik-crs326-24s",
      price: 449,
      currency: "GBP",
      stockStatus: "in_stock",
      url: "https://linitx.com/product/mikrotik-crs326-24s-2q-rm/17890",
      lastChecked: new Date().toISOString(),
      priceHistory: [
        {
          date: new Date(Date.now() - 86400000 * 60).toISOString(),
          price: 475,
          currency: "GBP",
          stockStatus: "in_stock",
        },
        {
          date: new Date(Date.now() - 86400000 * 30).toISOString(),
          price: 465,
          currency: "GBP",
          stockStatus: "in_stock",
        },
        {
          date: new Date(Date.now() - 86400000 * 14).toISOString(),
          price: 455,
          currency: "GBP",
          stockStatus: "in_stock",
        },
        {
          date: new Date().toISOString(),
          price: 449,
          currency: "GBP",
          stockStatus: "in_stock",
        },
      ],
    },
    {
      distributorId: "server2u-my",
      productId: "mikrotik-crs326-24s",
      price: 2180,
      currency: "MYR",
      stockStatus: "in_stock",
      url: "https://server2u.com/shop/crs326-24s-2q-rm",
      lastChecked: new Date().toISOString(),
      priceHistory: [
        {
          date: new Date(Date.now() - 86400000 * 60).toISOString(),
          price: 2350,
          currency: "MYR",
          stockStatus: "in_stock",
        },
        {
          date: new Date(Date.now() - 86400000 * 30).toISOString(),
          price: 2280,
          currency: "MYR",
          stockStatus: "in_stock",
        },
        {
          date: new Date(Date.now() - 86400000 * 14).toISOString(),
          price: 2240,
          currency: "MYR",
          stockStatus: "in_stock",
        },
        {
          date: new Date().toISOString(),
          price: 2180,
          currency: "MYR",
          stockStatus: "in_stock",
        },
      ],
    },
    {
      distributorId: "duxtel-au",
      productId: "mikrotik-crs326-24s",
      price: 899,
      currency: "AUD",
      stockStatus: "back_order",
      expectedDate: "Aug 30, 2026",
      url: "https://store.duxtel.com.au/product/crs326-24s-2q-rm",
      lastChecked: new Date().toISOString(),
      priceHistory: [
        {
          date: new Date(Date.now() - 86400000 * 30).toISOString(),
          price: 950,
          currency: "AUD",
          stockStatus: "in_stock",
        },
        {
          date: new Date(Date.now() - 86400000 * 14).toISOString(),
          price: 930,
          currency: "AUD",
          stockStatus: "back_order",
        },
        {
          date: new Date().toISOString(),
          price: 899,
          currency: "AUD",
          stockStatus: "back_order",
        },
      ],
    },
    {
      distributorId: "miro-za",
      productId: "mikrotik-crs326-24s",
      price: 11500,
      currency: "ZAR",
      stockStatus: "back_order",
      expectedDate: "Sept 5, 2026",
      url: "https://miro.co.za/networking/crs326-24s-2q-rm",
      lastChecked: new Date().toISOString(),
      priceHistory: [
        {
          date: new Date(Date.now() - 86400000 * 30).toISOString(),
          price: 12000,
          currency: "ZAR",
          stockStatus: "in_stock",
        },
        {
          date: new Date(Date.now() - 86400000 * 14).toISOString(),
          price: 11800,
          currency: "ZAR",
          stockStatus: "back_order",
        },
        {
          date: new Date().toISOString(),
          price: 11500,
          currency: "ZAR",
          stockStatus: "back_order",
        },
      ],
    },
    {
      distributorId: "getic-gr",
      productId: "mikrotik-crs326-24s",
      price: 398,
      currency: "EUR",
      stockStatus: "out_of_stock",
      url: "https://www.getic.com/product/mikrotik-crs326-24s-2q-rm",
      lastChecked: new Date().toISOString(),
      priceHistory: [
        {
          date: new Date(Date.now() - 86400000 * 30).toISOString(),
          price: 395,
          currency: "EUR",
          stockStatus: "in_stock",
        },
        {
          date: new Date(Date.now() - 86400000 * 14).toISOString(),
          price: 397,
          currency: "EUR",
          stockStatus: "out_of_stock",
        },
        {
          date: new Date().toISOString(),
          price: 398,
          currency: "EUR",
          stockStatus: "out_of_stock",
        },
      ],
    },
  ],
};
