import type { Distributor } from "@/lib/types";

export const DISTRIBUTORS: Distributor[] = [
  {
    id: "server2u-my",
    name: "Server2U",
    currency: "MYR",
    country: "Malaysia",
    countryFlag: "🇲🇾",
    region: "Asia-Pacific",
    website: "https://server2u.com",
    paymentMethods: ["Credit Card", "Online Payment"],
    notes: "In-stock, fastest to Thailand",
    shippingCosts: {
      "Asia-Pacific": 15,
      Europe: 40,
      "North America": 45,
      "Middle East": 35,
      Africa: 50,
    },
  },
  {
    id: "linitx-uk",
    name: "Linitx",
    currency: "GBP",
    country: "United Kingdom",
    countryFlag: "🇬🇧",
    region: "Europe",
    website: "https://linitx.com",
    paymentMethods: [
      "Credit Card",
      "Bank Transfer",
      "Apple Pay",
      "Revolut Pay",
      "Invoice",
    ],
    shippingCosts: {
      Europe: 12,
      "North America": 35,
      "Asia-Pacific": 40,
      "Middle East": 30,
      Africa: 45,
    },
  },
  {
    id: "interprojekt-pl",
    name: "Inter Projekt",
    currency: "EUR",
    country: "Poland",
    countryFlag: "🇵🇱",
    region: "Europe",
    website: "https://interprojekt.pl",
    paymentMethods: ["Online Payment", "Bank Transfer", "Credit Card"],
    notes: "Best overall price",
    shippingCosts: {
      Europe: 18,
      "North America": 38,
      "Asia-Pacific": 42,
      "Middle East": 32,
      Africa: 48,
    },
  },
  {
    id: "nasstore-eu",
    name: "NAS Store EU",
    currency: "EUR",
    country: "European Union",
    countryFlag: "🇪🇺",
    region: "Europe",
    website: "https://nasstore.eu",
    paymentMethods: [
      "Credit Card",
      "Bank Transfer",
      "Apple Pay",
      "Revolut Pay",
    ],
    notes: "Best August price",
    shippingCosts: {
      Europe: 16,
      "North America": 36,
      "Asia-Pacific": 40,
      "Middle East": 32,
      Africa: 46,
    },
  },
  {
    id: "aerial-gr",
    name: "Aerial.net",
    currency: "EUR",
    country: "Greece",
    countryFlag: "🇬🇷",
    region: "Europe",
    website: "https://aerial.net",
    paymentMethods: ["Credit Card", "Bank Transfer"],
    shippingCosts: {
      Europe: 20,
      "North America": 40,
      "Asia-Pacific": 44,
      "Middle East": 34,
      Africa: 50,
    },
  },
  {
    id: "mikrotikstore-de",
    name: "MikroTik Store EU",
    currency: "EUR",
    country: "Germany",
    countryFlag: "🇩🇪",
    region: "Europe",
    website: "https://mikrotik-store.eu",
    paymentMethods: ["Credit Card", "PayPal", "Bank Transfer"],
    notes: "Official MikroTik certified distributor",
    shippingCosts: {
      Europe: 14,
      "North America": 34,
      "Asia-Pacific": 38,
      "Middle East": 30,
      Africa: 44,
    },
  },
  {
    id: "miro-za",
    name: "MiRO Distribution",
    currency: "ZAR",
    country: "South Africa",
    countryFlag: "🇿🇦",
    region: "Africa",
    website: "https://miro.co.za",
    paymentMethods: ["Credit Card", "EFT"],
    shippingCosts: {
      Africa: 20,
      Europe: 35,
      "North America": 45,
      "Asia-Pacific": 50,
      "Middle East": 40,
    },
  },
  {
    id: "gearup-ae",
    name: "Gear-Up.me",
    currency: "AED",
    country: "UAE",
    countryFlag: "🇦🇪",
    region: "Middle East",
    website: "https://gear-up.me",
    paymentMethods: ["Credit Card", "Bank Transfer"],
    notes: "24-month local warranty",
    shippingCosts: {
      "Middle East": 15,
      Europe: 30,
      "Asia-Pacific": 35,
      "North America": 40,
      Africa: 38,
    },
  },
  {
    id: "balticnetworks-us",
    name: "Baltic Networks",
    currency: "USD",
    country: "United States",
    countryFlag: "🇺🇸",
    region: "North America",
    website: "https://balticnetworks.com",
    paymentMethods: ["Wire Transfer"],
    notes: "Wire transfer only",
    shippingCosts: {
      "North America": 18,
      Europe: 40,
      "Middle East": 45,
      "Asia-Pacific": 55,
      Africa: 60,
    },
  },
  {
    id: "linktechs-us",
    name: "Link Technologies",
    currency: "USD",
    country: "United States",
    countryFlag: "🇺🇸",
    region: "North America",
    website: "https://shop.linktechs.net",
    paymentMethods: ["Wire Transfer"],
    notes: "Wire transfer only",
    shippingCosts: {
      "North America": 20,
      Europe: 42,
      "Middle East": 47,
      "Asia-Pacific": 57,
      Africa: 62,
    },
  },
  {
    id: "winncom-us",
    name: "Winncom",
    currency: "USD",
    country: "United States",
    countryFlag: "🇺🇸",
    region: "North America",
    website: "https://winncom.com",
    paymentMethods: ["Credit Card", "Bank Transfer"],
    shippingCosts: {
      "North America": 15,
      Europe: 38,
      "Middle East": 43,
      "Asia-Pacific": 53,
      Africa: 58,
    },
  },
  {
    id: "bhphoto-us",
    name: "B&H Photo Video",
    currency: "USD",
    country: "United States",
    countryFlag: "🇺🇸",
    region: "North America",
    website: "https://bhphotovideo.com",
    paymentMethods: ["Credit Card", "PayPal", "Financing"],
    shippingCosts: {
      "North America": 12,
      Europe: 36,
      "Middle East": 41,
      "Asia-Pacific": 51,
      Africa: 56,
    },
  },
  {
    id: "duxtel-au",
    name: "DuxTel",
    currency: "AUD",
    country: "Australia",
    countryFlag: "🇦🇺",
    region: "Asia-Pacific",
    website: "https://store.duxtel.com",
    paymentMethods: ["Credit Card", "Bank Transfer"],
    shippingCosts: {
      "Asia-Pacific": 15,
      Europe: 45,
      "North America": 55,
      "Middle East": 40,
      Africa: 60,
    },
  },
  {
    id: "wisp-au",
    name: "WISP",
    currency: "AUD",
    country: "Australia",
    countryFlag: "🇦🇺",
    region: "Asia-Pacific",
    website: "https://wisp.net.au",
    paymentMethods: ["Credit Card"],
    shippingCosts: {
      "Asia-Pacific": 12,
      Europe: 42,
      "North America": 52,
      "Middle East": 38,
      Africa: 58,
    },
  },
  {
    id: "pbtech-nz",
    name: "PB Tech",
    currency: "NZD",
    country: "New Zealand",
    countryFlag: "🇳🇿",
    region: "Asia-Pacific",
    website: "https://pbtech.co.nz",
    paymentMethods: ["Credit Card", "Bank Transfer", "Afterpay"],
    shippingCosts: {
      "Asia-Pacific": 10,
      Europe: 38,
      "North America": 48,
      "Middle East": 35,
      Africa: 55,
    },
  },
  {
    id: "gowifi-nz",
    name: "GoWiFi",
    currency: "NZD",
    country: "New Zealand",
    countryFlag: "🇳🇿",
    region: "Asia-Pacific",
    website: "https://gowifi.co.nz",
    paymentMethods: ["Credit Card"],
    shippingCosts: {
      "Asia-Pacific": 8,
      Europe: 36,
      "North America": 46,
      "Middle East": 33,
      Africa: 53,
    },
  },
  {
    id: "getic-gr",
    name: "Getic",
    currency: "EUR",
    country: "Greece",
    countryFlag: "🇬🇷",
    region: "Europe",
    website: "https://getic.com",
    paymentMethods: ["Credit Card", "Bank Transfer"],
    shippingCosts: {
      Europe: 18,
      "North America": 40,
      "Asia-Pacific": 44,
      "Middle East": 34,
      Africa: 50,
    },
  },
  {
    id: "100mega-cz",
    name: "100MEGA Distribution",
    currency: "EUR",
    country: "Czech Republic",
    countryFlag: "🇨🇿",
    region: "Europe",
    website: "https://b2b.100mega.com",
    paymentMethods: ["Bank Transfer", "Credit Card"],
    shippingCosts: {
      Europe: 20,
      "North America": 42,
      "Asia-Pacific": 46,
      "Middle East": 36,
      Africa: 52,
    },
  },
  {
    id: "hellascom-gr",
    name: "HellasCom",
    currency: "EUR",
    country: "Greece",
    countryFlag: "🇬🇷",
    region: "Europe",
    website: "https://hellascom.gr",
    paymentMethods: ["Credit Card", "Bank Transfer"],
    notes: "MikroTik distributor since 2001, ISO 9001:2015",
    shippingCosts: {
      Europe: 17,
      "North America": 38,
      "Asia-Pacific": 42,
      "Middle East": 33,
      Africa: 48,
    },
  },
  {
    id: "rocnoc-us",
    name: "ROC-NOC",
    currency: "USD",
    country: "United States",
    countryFlag: "🇺🇸",
    region: "North America",
    website: "https://roc-noc.com",
    paymentMethods: ["Credit Card", "Bank Transfer"],
    shippingCosts: {
      "North America": 16,
      Europe: 40,
      "Middle East": 45,
      "Asia-Pacific": 55,
      Africa: 60,
    },
  },
  {
    id: "networkdevices-us",
    name: "Network Devices Inc",
    currency: "USD",
    country: "United States",
    countryFlag: "🇺🇸",
    region: "North America",
    website: "https://networkdevicesinc.com",
    paymentMethods: ["Credit Card", "Bank Transfer"],
    shippingCosts: {
      "North America": 18,
      Europe: 42,
      "Middle East": 47,
      "Asia-Pacific": 57,
      Africa: 62,
    },
  },
  {
    id: "flytec-us",
    name: "Flytec Computers",
    currency: "USD",
    country: "United States",
    countryFlag: "🇺🇸",
    region: "North America",
    website: "https://flyteccomputers.com",
    paymentMethods: ["Credit Card"],
    shippingCosts: {
      "North America": 14,
      Europe: 38,
      "Middle East": 43,
      "Asia-Pacific": 53,
      Africa: 58,
    },
  },
  {
    id: "mbsiwav-ca",
    name: "MBS I-WAV",
    currency: "CAD",
    country: "Canada",
    countryFlag: "🇨🇦",
    region: "North America",
    website: "https://mbsiwav.com",
    paymentMethods: ["Credit Card", "Bank Transfer"],
    shippingCosts: {
      "North America": 20,
      Europe: 42,
      "Middle East": 47,
      "Asia-Pacific": 57,
      Africa: 62,
    },
  },
  {
    id: "multilink-us",
    name: "Multilink",
    currency: "USD",
    country: "United States",
    countryFlag: "🇺🇸",
    region: "North America",
    website: "https://shop.multilink.us",
    paymentMethods: ["Credit Card"],
    shippingCosts: {
      "North America": 12,
      Europe: 36,
      "Middle East": 41,
      "Asia-Pacific": 51,
      Africa: 56,
    },
  },
  {
    id: "neobits-us",
    name: "Neobits",
    currency: "USD",
    country: "United States",
    countryFlag: "🇺🇸",
    region: "North America",
    website: "https://neobits.com",
    paymentMethods: ["Credit Card", "PayPal"],
    shippingCosts: {
      "North America": 12,
      Europe: 36,
      "Middle East": 41,
      "Asia-Pacific": 51,
      Africa: 56,
    },
  },
  {
    id: "newegg-us",
    name: "Newegg",
    currency: "USD",
    country: "United States",
    countryFlag: "🇺🇸",
    region: "North America",
    website: "https://www.newegg.com",
    paymentMethods: ["Credit Card", "PayPal"],
    shippingCosts: {
      "North America": 10,
      Europe: 35,
      "Middle East": 40,
      "Asia-Pacific": 50,
      Africa: 55,
    },
  },
  {
    id: "apple-us",
    name: "Apple Store",
    currency: "USD",
    country: "United States",
    countryFlag: "🇺🇸",
    region: "North America",
    website: "https://www.apple.com",
    paymentMethods: ["Credit Card", "Apple Pay"],
    shippingCosts: {
      "North America": 0,
      Europe: 25,
      "Middle East": 30,
      "Asia-Pacific": 35,
      Africa: 45,
    },
  },
  {
    id: "pimoroni-uk",
    name: "Pimoroni",
    currency: "GBP",
    country: "United Kingdom",
    countryFlag: "🇬🇧",
    region: "Europe",
    website: "https://shop.pimoroni.com",
    paymentMethods: ["Credit Card", "PayPal"],
    shippingCosts: {
      Europe: 8,
      "North America": 30,
      "Middle East": 28,
      "Asia-Pacific": 38,
      Africa: 42,
    },
  },
  {
    id: "allasch-uk",
    name: "Allied Electronics",
    currency: "GBP",
    country: "United Kingdom",
    countryFlag: "🇬🇧",
    region: "Europe",
    website: "https://www.alliedelec.com",
    paymentMethods: ["Credit Card", "Bank Transfer"],
    shippingCosts: {
      Europe: 10,
      "North America": 32,
      "Middle East": 30,
      "Asia-Pacific": 40,
      Africa: 44,
    },
  },
  {
    id: "valve-us",
    name: "Steam",
    currency: "USD",
    country: "United States",
    countryFlag: "🇺🇸",
    region: "North America",
    website: "https://store.steampowered.com",
    paymentMethods: ["Credit Card", "PayPal"],
    shippingCosts: {
      "North America": 8,
      Europe: 28,
      "Middle East": 33,
      "Asia-Pacific": 43,
      Africa: 48,
    },
  },
];

export function getDistributorById(id: string): Distributor | undefined {
  return DISTRIBUTORS.find((d) => d.id === id);
}

export async function getAllDistributors() {
  return [...DISTRIBUTORS];
}
